server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/salarymanage
    username: root
    password: 1234
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html

  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
